name: SizeFFA
main: ThePammYT\SizeFFA\Main
version: 0.0.1
api: [ 1.0.0 , 2.0.0 , 3.0.0 ]
load: POSTWORLD
author: ThePammYT
description: SizeFFA
website: https://fuzzyleap.ml

commands:
 sffa:
  description: "SizeFFA"
  usage: "/sffa option"
  permission: sizeffa.command.op

permissions:
 sizeffa.command:
  default: op
  description: "Example root permission node"
  children:
   sizeffa.command.op:
    default: op
    description: "Allows the use of /sizeffa"
